my_str = "i'm pragya priya srivastava"

int = 100

float = 1.5

my_set = {"p","r","a","g","y","a"}

dict = {"name":"pragya","sem":"4",}

list = ["os","java"]

tuple = ("java",12,1.5)

com_num = 12j + 34

print("the basic data structure are: \n")

print("type is:",type(my_set))
print(my_set)

print("type is:",type(my_str))
print(my_str)

print("type is:",type(list))
print(list)

print("type is:",type(tuple))
print(tuple)

print("type is:",type(com_num))
print(com_num)

print("type is:",type(dict))
print(dict)

print("type is:",type(int))
print(int)

print("type is:",type(float))
print(float)
